### ISSUE TITLE
Add further tests

### ISSUE THREAD

**Issue by JakobBD** [pik-piam/sodym#4]

**Comment by SallyDa** [comment]
I was thinking of tests for simson directly; i.e. testing the model equations with the mass conversation check that you currently have. I haven't thought about tests for sodym yet, but of course it would also be good to have some!

**Comment by JakobBD** [comment]
At least the get_relative_mass_balance function is so general (and generally needed) that I think it should stay in sodym.
Looking at it, we could actually split it to a get_mass_balance and one which divides that value by the total.

I have no strong opinion of whether to leave it in the MFASystem class or move it outside. 

As for the check_mass_balance function, we could definitely move it outside the MFASystem object. It's also quite general and other sodym users might find it useful? 

In general, I find it hard to judge if a sodym testing suite makes sense and is worth the effort. Let's talk in person.

**Comment by SallyDa** [comment]
I think it should be a test that can be run on all child classes of the MFASystem. It should be in a separate testing file imo, since it does not need to be run every time the model is run (if the data is changed, but the model is the same, we don't need to check the test will still pass). It only needs to run when there are model changes and e.g. could be automated to run in github when new PRs are created. Agree that it is useful to have it in the sodym package still, but not sure how this would work in practice, since we need to run it on classes defined in simson, but I guess it is possible.
